export default [
  {
    img: "./diwakar.png",
    name: "Diwakar",
    id: "N210242",
    year: "E-02",
    branch: "CSE",
  },
  {
    img: "./profile.png",
    name: "Maruthi",
    id: "N210242",
    year: "E-02",
    branch: "CSE",
  },
  {
    img: "./profile.png",
    name: "Siddartha",
    id: "N210242",
    year: "E-02",
    branch: "CSE",
  },
  {
    img: "./profile.png",
    name: "Karthik",
    id: "N210242",
    year: "E-02",
    branch: "CSE",
  },
  {
    img: "./profile.png",
    name: "Diwakar",
    id: "N210242",
    year: "E-02",
    branch: "CSE",
  },
  {
    img: "./profile.png",
    name: "Diwakar",
    id: "N210242",
    year: "E-02",
    branch: "CSE",
  },
  {
    img: "./profile.png",
    name: "Diwakar",
    id: "N210242",
    year: "E-02",
    branch: "CSE",
  },
  {
    img: "./profile.png",
    name: "Diwakar",
    id: "N210242",
    year: "E-02",
    branch: "CSE",
  },
  {
    img: "./profile.png",
    name: "Diwakar",
    id: "N210242",
    year: "E-02",
    branch: "CSE",
  },
];
